### ISSUE TITLE
Prevent PHP warnings on urls that don't have post objects

### ISSUE THREAD

**Issue by lecklin** [rentle/embed-rentle#25]
The plugin throws php warnings on site urls that don't have post objects, so pages like 404 and most likely other scenarios.
The warnings:

> PHP Warning: Attempt to read property "ID" on null in /data/wordpress/htdocs/wp-content/plugins/embed-rentle/src/init.php on line 33
> PHP Warning: Attempt to read property "post_content" on null in /data/wordpress/htdocs/wp-content/plugins/embed-rentle/src/init.php on line 33

It's pretty clear why this happens, so should be an easy fix.
You can see on the line in question that the plugin assumes `$post` and subsequently `$post->ID`/`$post->post_content` exist, when in reality they might not.

This is more of an annoyance from logs being filled up than an actual issue, but anyhoo.
Cheers.

**Comment by luuptekman** [comment]
Thanks for the report 👍  This will be fixed in upcoming version 1.3.1.

**Comment by luuptekman** [comment]
Fix is now finally pushed to plugins repo (as well as this github repo)
